/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import api_call.OpenWeatherCall;
import api_current_weather.CurrentWeather;
import bl.CountryCodes;
import bl.ImageIconScalar;
import java.awt.Image;

/**
 *
 * @author elisc
 */
public class CompareWeatherConditionsGUI extends javax.swing.JFrame {

    /**
     * Creates new form CompareWeatherConditionsGUI
     */
    public CompareWeatherConditionsGUI() {
        initComponents();
        setVisible(true);
        setSize(600, 400);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void showConditions(CurrentWeather[] conditions) {
        OpenWeatherCall call = new OpenWeatherCall();
        ImageIconScalar scalar = new ImageIconScalar();
        CurrentWeather weather1 = conditions[0];
        CurrentWeather weather2 = conditions[1];

        Image image1 = call.getWeatherIcon(weather1.getWeather().get(0).getIcon());
        lbIcon1.setIcon(scalar.getScaledImageIcon(image1, 50, 50));

        Image image2 = call.getWeatherIcon(weather2.getWeather().get(0).getIcon());
        lbIcon2.setIcon(scalar.getScaledImageIcon(image2, 50, 50));

        lbName1.setText(weather1.getName() + ", "
                + CountryCodes.getInstance()
                        .getValue(weather1.getSys().getCountry()));
        lbName2.setText(weather2.getName() + ", "
                + CountryCodes.getInstance()
                        .getValue(weather2.getSys().getCountry()));

        lbCurrentTemp1.setText(weather1.getMain().getTemp() + " °C");
        lbCurrentTemp2.setText(weather2.getMain().getTemp() + " °C");

        lbMaxTemp1.setText(weather1.getMain().getTemp_max() + " °C");
        lbMaxTemp2.setText(weather2.getMain().getTemp_max() + " °C");

        lbMinTemp1.setText(weather1.getMain().getTemp_min() + " °C");
        lbMinTemp2.setText(weather2.getMain().getTemp_min() + " °C");

        lbPressure1.setText(weather1.getMain().getPressure() + " Pa");
        lbPressure2.setText(weather2.getMain().getPressure() + " Pa");

        lbHumidity1.setText(weather1.getMain().getHumidity() + " %");
        lbHumidity2.setText(weather2.getMain().getHumidity() + " %");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCondition1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbIcon1 = new javax.swing.JLabel();
        lbName1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbCurrentTemp1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbMaxTemp1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbMinTemp1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbPressure1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbHumidity1 = new javax.swing.JLabel();
        pCondition2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbIcon2 = new javax.swing.JLabel();
        lbName2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbCurrentTemp2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbMaxTemp2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbMinTemp2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbPressure2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbHumidity2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        pCondition1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCondition1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        lbIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbIcon1);

        lbName1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbName1);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Current Temp");
        jPanel13.add(jLabel9);

        lbCurrentTemp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lbCurrentTemp1);

        jPanel1.add(jPanel13);

        pCondition1.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Max Temp");
        jPanel5.add(jLabel1);

        lbMaxTemp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbMaxTemp1);

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Min Temp");
        jPanel6.add(jLabel3);

        lbMinTemp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(lbMinTemp1);

        jPanel2.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pressure");
        jPanel7.add(jLabel2);

        lbPressure1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(lbPressure1);

        jPanel2.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Humidity");
        jPanel8.add(jLabel4);

        lbHumidity1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(lbHumidity1);

        jPanel2.add(jPanel8);

        pCondition1.add(jPanel2);

        getContentPane().add(pCondition1);

        pCondition2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCondition2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        lbIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lbIcon2);

        lbName2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lbName2);

        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Current Temp");
        jPanel14.add(jLabel10);

        lbCurrentTemp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lbCurrentTemp2);

        jPanel3.add(jPanel14);

        pCondition2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridLayout(2, 2));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Max Temp");
        jPanel9.add(jLabel5);

        lbMaxTemp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(lbMaxTemp2);

        jPanel4.add(jPanel9);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Min Temp");
        jPanel12.add(jLabel7);

        lbMinTemp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lbMinTemp2);

        jPanel4.add(jPanel12);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pressure");
        jPanel11.add(jLabel8);

        lbPressure2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lbPressure2);

        jPanel4.add(jPanel11);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Humidity");
        jPanel10.add(jLabel6);

        lbHumidity2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(lbHumidity2);

        jPanel4.add(jPanel10);

        pCondition2.add(jPanel4);

        getContentPane().add(pCondition2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompareWeatherConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompareWeatherConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompareWeatherConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompareWeatherConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompareWeatherConditionsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbCurrentTemp1;
    private javax.swing.JLabel lbCurrentTemp2;
    private javax.swing.JLabel lbHumidity1;
    private javax.swing.JLabel lbHumidity2;
    private javax.swing.JLabel lbIcon1;
    private javax.swing.JLabel lbIcon2;
    private javax.swing.JLabel lbMaxTemp1;
    private javax.swing.JLabel lbMaxTemp2;
    private javax.swing.JLabel lbMinTemp1;
    private javax.swing.JLabel lbMinTemp2;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbPressure1;
    private javax.swing.JLabel lbPressure2;
    private javax.swing.JPanel pCondition1;
    private javax.swing.JPanel pCondition2;
    // End of variables declaration//GEN-END:variables

}
