/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import api_call.OpenWeatherCall;
import api_current_weather.CurrentWeather;
import api_forecast.WeatherForecast;
import bl.CountryCodes;
import bl.DTF;
import bl.ForecastParser;
import bl.TravelSoftwareTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.JTableHeader;

/**
 *
 * @author elisc
 */
public class TravelSoftwareGUI extends javax.swing.JFrame {

    private TravelSoftwareTableModel model;
    private TravelSoftwareTableCellRenderer renderer;

    /**
     * Creates new form MainGUI
     */
    public TravelSoftwareGUI() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDate = new javax.swing.JComboBox<>();
        lbLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDestination = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btAddDestination = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btRemoveDestination = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("City");
        jPanel3.add(jLabel1);
        jPanel3.add(txCity);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Country (refer to ISO 3166)");
        jPanel3.add(jLabel3);

        cbCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCountryActionPerformed(evt);
            }
        });
        jPanel3.add(cbCountry);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Day of Departure");
        jPanel3.add(jLabel2);

        jPanel3.add(cbDate);

        lbLogo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("Weather Report");

        tbDestination.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDestination);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        btAddDestination.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAddDestination.setText("Add Destination");
        btAddDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddDestinationActionPerformed(evt);
            }
        });
        jPanel1.add(btAddDestination);
        jPanel1.add(jLabel4);

        btRemoveDestination.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btRemoveDestination.setText("Remove Destination");
        btRemoveDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveDestinationActionPerformed(evt);
            }
        });
        jPanel1.add(btRemoveDestination);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddDestinationActionPerformed
        String city = txCity.getText();
        String country = CountryCodes.getInstance()
                .getValue((String) cbCountry.getSelectedItem());

        addData(city, country);
    }//GEN-LAST:event_btAddDestinationActionPerformed

    private void btRemoveDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveDestinationActionPerformed
        int[] indices = tbDestination.getSelectedRows();
        model.remove(indices);
    }//GEN-LAST:event_btRemoveDestinationActionPerformed

    private void cbCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCountryActionPerformed

    private void fillDateCb() {
        LocalDate date = LocalDate.now();

        for (int i = 0; i < 5; i++) {
            String dateStr = date.plusDays((long) i).format(DTF.STANDARD_DATE.value());
            cbDate.addItem(dateStr);
        }
    }

    private void fillCountryCb() {
        for (String key : CountryCodes.getInstance().getCountries()) {
            cbCountry.addItem(key);
        }
    }

    private void changeForecastModel() {
        ArrayList<CurrentWeather> data = new ArrayList<>();
        data.addAll(model.getWeatherData());
        model.clearTable();

        for (CurrentWeather currentWeather : data) {
            addData(currentWeather.getName(),
                    currentWeather.getSys().getCountry());
        }
    }

    private void addData(String city, String country) {
        CurrentWeather weather = null;

        LocalDate selectedDate = LocalDate
                .parse((String) cbDate.getSelectedItem(),
                        DTF.STANDARD_DATE.value());

        if (selectedDate.equals(LocalDate.now())) {
            weather = OpenWeatherCall
                    .getInstance().getCurrentWeatherByCityAndCountry(city, country);
        } else {
            WeatherForecast forecast = OpenWeatherCall.getInstance().getForecastByCityAndCountry(city, country);
            weather = new ForecastParser().parseForecastToCurrentWeather(forecast, selectedDate);
        }

        model.add(weather);
    }

    private void init() {
        model = new TravelSoftwareTableModel();
        renderer = new TravelSoftwareTableCellRenderer();

        cbDate.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                changeForecastModel();
            }
        });

        JTableHeader header = tbDestination.getTableHeader();
        header.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent event) {
                if (event.getButton() == MouseEvent.BUTTON1) {
                    int colid = tbDestination.columnAtPoint(event.getPoint());
                    model.sortColumn("" + header.getColumnModel()
                            .getColumn(colid).getHeaderValue());
                }
            }
        });

        fillDateCb();
        fillCountryCb();

        model.load();
        tbDestination.setModel(model);
        tbDestination.setDefaultRenderer(Object.class, renderer);
        tbDestination.setRowHeight(30);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelSoftwareGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddDestination;
    private javax.swing.JButton btRemoveDestination;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JComboBox<String> cbDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTable tbDestination;
    private javax.swing.JTextField txCity;
    // End of variables declaration//GEN-END:variables
}
