/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import api_call.OpenWeatherCall;
import api_response.OpenWeatherData;
import bl.TravelSoftwareTableModel;

/**
 *
 * @author elisc
 */
public class TravelSoftwareGUI extends javax.swing.JFrame {

    private TravelSoftwareTableModel model = new TravelSoftwareTableModel();
    private TravelSoftwareTableCellRenderer renderer = new TravelSoftwareTableCellRenderer();

    /**
     * Creates new form MainGUI
     */
    public TravelSoftwareGUI() {
        initComponents();

        model.load();
        tbDestination.setModel(model);
        tbDestination.setDefaultRenderer(Object.class, renderer);
        tbDestination.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDate = new javax.swing.JComboBox<>();
        lbLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDestination = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btAddDestination = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btRemoveDestination = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("City");
        jPanel3.add(jLabel1);
        jPanel3.add(txCity);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Country (refer to ISO 3166)");
        jPanel3.add(jLabel3);

        jPanel3.add(cbCountry);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Day of Departure");
        jPanel3.add(jLabel2);

        jPanel3.add(cbDate);

        lbLogo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("Weather Report");

        tbDestination.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDestination);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        btAddDestination.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btAddDestination.setText("Add Destination");
        btAddDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddDestinationActionPerformed(evt);
            }
        });
        jPanel1.add(btAddDestination);
        jPanel1.add(jLabel4);

        btRemoveDestination.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btRemoveDestination.setText("Remove Destination");
        btRemoveDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveDestinationActionPerformed(evt);
            }
        });
        jPanel1.add(btRemoveDestination);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddDestinationActionPerformed
        OpenWeatherCall call = new OpenWeatherCall();
        String city = txCity.getText();
        String country = (String) cbCountry.getSelectedItem();
        OpenWeatherData weather;

        /*if(!country.equals("")){
            weather = call.getWeatherForecastByCityAndCountry(city, country);
        }
        else{
            weather = call.getWeatherForecastByCity(city);
        }*/
        weather = call.getWeatherForecastByCity(city);
        model.add(weather);
    }//GEN-LAST:event_btAddDestinationActionPerformed

    private void btRemoveDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveDestinationActionPerformed
        int[] indices = tbDestination.getSelectedRows();
        model.remove(indices);
    }//GEN-LAST:event_btRemoveDestinationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelSoftwareGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelSoftwareGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddDestination;
    private javax.swing.JButton btRemoveDestination;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JComboBox<String> cbDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTable tbDestination;
    private javax.swing.JTextField txCity;
    // End of variables declaration//GEN-END:variables
}
